//
//  Local.swift
//  Translate it
//
//  Created by iMac on 01/09/21.
//

import Foundation

extension String {
    static let introDes = "introDes"
    static let getStarted = "getStarted"
    static let loginDes = "loginDes"
    static let signInToContinue = "signInToContinue"
    static let signInWithApple = "signInWithApple"
    static let signInWithGoogle = "signInWithGoogle"
    static let signInWithEmail = "signInWithEmail"
    static let signIn = "signIn"
    static let signUp = "signUp"
    static let email = "email"
    static let password = "password"
    static let fullName = "fullName"
    static let confirmPassword = "confirmPassword"
    static let forgetPassword = "forgetPassword"
    static let forgetPasswordDes = "forgetPasswordDes"
    static let reset = "reset"
    static let inspirationForYou = "inspirationForYou"
    static let plays = "plays"
    static let home = "home"
    static let category = "category"
    static let article = "article"
    static let favourites = "favourites"
    static let mySpace = "mySpace"
    static let searchHear = "searchHear"
    static let tracks = "tracks"
    static let articles = "articles"
    static let becomeA = "becomeA"
    static let pro = "pro"
    static let notifications = "notifications"
    static let language = "language"
    static let privacyPolicy = "privacyPolicy"
    static let rateThisApp = "rateThisApp"
    static let logOut = "logOut"
    static let deleteMyAccount = "deleteMyAccount"
    static let edit = "edit"
    static let editProfile = "editProfile"
    static let update = "update"
    static let restore = "restore"
    static let subscribeTo = "subscribeTo"
    static let subscribeToDes = "subscribeToDes"
    static let monthly = "monthly"
    static let monthlyDes = "monthlyDes"
    static let yearly = "yearly"
    static let yearlyDes = "yearlyDes"
    static let whyGoWith = "whyGoWith"
    static let fullyAdFree = "fullyAdFree"
    static let accessToAll = "accessToAll"
    static let technicalSupport = "technicalSupport"
    static let cancelAnyTime = "cancelAnyTime"
    static let proRegulations = "proRegulations"
    static let subscribe = "subscribe"
    static let proQ = "proQ"
    static let areYouSure = "areYouSure"
    static let logOutDes = "logOutDes"
    static let deleteDes = "deleteDes"
    static let subscribeToPro = "subscribeToPro"
    static let subscribeToProDes = "subscribeToProDes"
    static let becomeAPro = "becomeAPro"
    static let selectLanguage = "selectLanguage"
    static let change = "change"
    static let yourName = "yourName"
    static let skip = "skip"
    static let noFavoirites = "noFavoirites"
    static let invalidEmailNPass = "invalidEmailNPass"
    static let passwordResetLinkSent = "passwordResetLinkSent"
    static let noAcFoundWithThisEmail = "noAcFoundWithThisEmail"
    static let youHaveSuccessfullyBecomePro = "youHaveSuccessfullyBecomePro"
    static let youAre = "youAre"
    static let passNotMatch = "passNotMatch"
    static let noDataFound = "noDataFound"
    static let timer = "timer"
    static let minutes = "minutes"
    static let customTimer = "customTimer"
    static let setTimer = "setTimer"
    static let musicWillBePause = "musicWillBePause"
    static let termsOfUse = "termsOfUse"
}
